added more fail-handeling

diff --git a/.github/workflows/release-integrations.yml b/.github/workflows/release-integrations.yml
--- a/.github/workflows/release-integrations.yml
+++ b/.github/workflows/release-integrations.yml
@@ -132,14 +132,18 @@ jobs:
             echo "📦 ${arch} digest: ${DIGEST}"
 
             LAYER_MANIFEST=$(docker buildx imagetools inspect "${IMAGE}@${DIGEST}" --raw)
-            if [[ -z "${LAYER_MANIFEST}" ]]; then
-              echo "⚠️ Failed to get layer manifest for ${arch}"
+            if [[ $? -ne 0 ]]; then
+              echo "⚠️ Failed to get layer manifest for ${arch} or layer manifest is null"
               continue
             fi
             SIZE=$(echo "${LAYER_MANIFEST}" | jq "[.layers[].size] | add")
+            if [[ $? -ne 0 ]]; then
+              echo "⚠️ Failed to add sizes for ${arch} or size is null"
+              continue
+            fi
 
             if [[ -z "${SIZE}" || "${SIZE}" == "null" ]]; then
-              echo "⚠️ Failed to get size for ${arch}"
+              echo "⚠️ Failed to get size for ${arch} or size is null"
               continue
             fi
 
