added more checks

diff --git a/.github/workflows/release-integrations.yml b/.github/workflows/release-integrations.yml
--- a/.github/workflows/release-integrations.yml
+++ b/.github/workflows/release-integrations.yml
@@ -117,7 +117,7 @@ jobs:
           set +e  # Don't exit on individual command failures
           IMAGE="ghcr.io/port-labs/port-ocean-${{ steps.prepare_tags.outputs.type }}:${{ steps.prepare_tags.outputs.version }}"
           MANIFEST=$(docker buildx imagetools inspect "${IMAGE}" --raw)
-          if [[ $? -ne 0 ]]; then
+          if [[ $? -ne 0 || -z "${MANIFEST}" || "${MANIFEST}" == "null" ]]; then
             echo "⚠️ Failed to get manifest for ${IMAGE}"
             continue
           fi
@@ -125,25 +125,20 @@ jobs:
           for arch in amd64 arm64; do
             DIGEST=$(echo "${MANIFEST}" | jq -r ".manifests[] | select(.platform.architecture==\"${arch}\") | .digest")
 
-            if [[ -z "${DIGEST}" || "${DIGEST}" == "null" ]]; then
-              echo "⚠️ Failed to get digest for ${arch}"
+            if [[ $? -ne 0 || -z "${DIGEST}" || "${DIGEST}" == "null" ]]; then
+              echo "⚠️ Failed to get digest for ${arch} or digest is null"
               continue
             fi
             echo "📦 ${arch} digest: ${DIGEST}"
 
             LAYER_MANIFEST=$(docker buildx imagetools inspect "${IMAGE}@${DIGEST}" --raw)
-            if [[ $? -ne 0 ]]; then
+            if [[ $? -ne 0 || -z "${LAYER_MANIFEST}" || "${LAYER_MANIFEST}" == "null" ]]; then
               echo "⚠️ Failed to get layer manifest for ${arch} or layer manifest is null"
               continue
             fi
             SIZE=$(echo "${LAYER_MANIFEST}" | jq "[.layers[].size] | add")
-            if [[ $? -ne 0 ]]; then
+            if [[ $? -ne 0 || -z "${SIZE}" || "${SIZE}" == "null" ]]; then
               echo "⚠️ Failed to add sizes for ${arch} or size is null"
-              continue
-            fi
-
-            if [[ -z "${SIZE}" || "${SIZE}" == "null" ]]; then
-              echo "⚠️ Failed to get size for ${arch} or size is null"
               continue
             fi
 
